# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test0():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_0(self):
    # Test name: 0
    # Step # | name | target | value
    # 1 | open | /adiJed/ui/login/page.jsp | 
    self.driver.get("http://172.16.90.4:8080/adiJed/ui/login/page.jsp")
    # 2 | setWindowSize | 1147x854 | 
    self.driver.set_window_size(1147, 854)
    # 3 | click | name=UN | 
    self.driver.find_element(By.NAME, "UN").click()
    # 4 | type | name=UN | mmalvicini
    self.driver.find_element(By.NAME, "UN").send_keys("mmalvicini")
    # 5 | click | name=PW | 
    self.driver.find_element(By.NAME, "PW").click()
    # 6 | type | name=PW | v54E2RDqwn
    self.driver.find_element(By.NAME, "PW").send_keys("v54E2RDqwn")
    # 7 | click | css=.login-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    # 8 | click | css=#query > span | 
    self.driver.find_element(By.CSS_SELECTOR, "#query > span").click()
    # 9 | click | css=.k-state-hover > .tree-item-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".k-state-hover > .tree-item-label").click()
    # 10 | click | id=F1008 | 
    self.driver.find_element(By.ID, "F1008").click()
    # 11 | type | id=F1008 | tuni032
    self.driver.find_element(By.ID, "F1008").send_keys("tuni032")
    # 12 | click | id=do-search | 
    self.driver.find_element(By.ID, "do-search").click()
    # 13 | click | css=.document-row:nth-child(1) input | 
    self.driver.find_element(By.CSS_SELECTOR, ".document-row:nth-child(1) input").click()
    # 14 | click | css=#viewSelected > div | 
    self.vars["window_handles"] = self.driver.window_handles
    # 15 | selectWindow | handle=${win4459} | 
    self.driver.find_element(By.CSS_SELECTOR, "#viewSelected > div").click()
    self.vars["win4459"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win4459"])
  
